/**
 * Techlysis — configuration, assets, timeframes, overlay defs
 */
const CONFIG = {
  assets: {
    XAUUSD: {
      id: 'XAUUSD',
      name: 'Gold',
      display: 'Gold (XAUUSD)',
      type: 'commodity',
      decimals: 2,
      tick: 0.01,
      // Free source mappings
      binance: null, // no native gold on binance spot
      yahoo: 'GC=F',
      stooq: 'gc.f',
      twelvedata: 'XAU/USD',
      unit: 'USD/oz',
    },
    EURUSD: {
      id: 'EURUSD',
      name: 'EUR/USD',
      display: 'EUR/USD',
      type: 'forex',
      decimals: 5,
      tick: 0.00001,
      binance: null,
      yahoo: 'EURUSD=X',
      stooq: 'eurusd',
      twelvedata: 'EUR/USD',
      unit: '',
    },
    USOIL: {
      id: 'USOIL',
      name: 'US Oil (WTI)',
      display: 'US Oil (WTI)',
      type: 'commodity',
      decimals: 2,
      tick: 0.01,
      binance: null,
      yahoo: 'CL=F',
      stooq: 'cl.f',
      twelvedata: 'WTI/USD',
      unit: 'USD/bbl',
    },
    GBPJPY: {
      id: 'GBPJPY',
      name: 'GBP/JPY',
      display: 'GBP/JPY',
      type: 'forex',
      decimals: 3,
      tick: 0.001,
      binance: null,
      yahoo: 'GBPJPY=X',
      stooq: 'gbpjpy',
      twelvedata: 'GBP/JPY',
      unit: '',
    },
    BTCUSD: {
      id: 'BTCUSD',
      name: 'Bitcoin',
      display: 'BTC/USD',
      type: 'crypto',
      decimals: 2,
      tick: 0.01,
      binance: 'BTCUSDT',
      yahoo: 'BTC-USD',
      stooq: 'btcusd',
      twelvedata: 'BTC/USD',
      unit: 'USD',
    },
    ETHUSD: {
      id: 'ETHUSD',
      name: 'Ethereum',
      display: 'ETH/USD',
      type: 'crypto',
      decimals: 2,
      tick: 0.01,
      binance: 'ETHUSDT',
      yahoo: 'ETH-USD',
      stooq: 'ethusd',
      twelvedata: 'ETH/USD',
      unit: 'USD',
    },
  },

  timeframes: {
    '1m':  { label: '1m',  minutes: 1,    binance: '1m',  yahoo: '1m',  stooq: '5' },
    '3m':  { label: '3m',  minutes: 3,    binance: '3m',  yahoo: '5m',  stooq: '5' },
    '5m':  { label: '5m',  minutes: 5,    binance: '5m',  yahoo: '5m',  stooq: '5' },
    '15m': { label: '15m', minutes: 15,   binance: '15m', yahoo: '15m', stooq: '60' },
    '30m': { label: '30m', minutes: 30,   binance: '30m', yahoo: '30m', stooq: '60' },
    '1h':  { label: '1h',  minutes: 60,   binance: '1h',  yahoo: '60m', stooq: '60' },
    '4h':  { label: '4h',  minutes: 240,  binance: '4h',  yahoo: '60m', stooq: 'd' },
    '1d':  { label: '1D',  minutes: 1440, binance: '1d',  yahoo: '1d',  stooq: 'd' },
  },

  /** Default overlay visibility */
  overlays: [
    { id: 'candles',     label: 'Candles',              color: '#e6edf7', default: true,  locked: true },
    { id: 'volume',      label: 'Volume bars',          color: '#3d9cf0', default: true },
    { id: 'ema9',        label: 'EMA 9',                color: '#22d3ee', default: true },
    { id: 'ema21',       label: 'EMA 21',               color: '#a78bfa', default: true },
    { id: 'ema50',       label: 'EMA 50',               color: '#f59e0b', default: true },
    { id: 'ema200',      label: 'EMA 200',              color: '#ec4899', default: false },
    { id: 'sma20',       label: 'SMA 20',               color: '#86efac', default: false },
    { id: 'bb',          label: 'Bollinger Bands',      color: '#5c6b7f', default: true },
    { id: 'vwap',        label: 'Session VWAP',         color: '#fb923c', default: false },
    { id: 'support',     label: 'Support levels',       color: '#22c55e', default: true },
    { id: 'resistance',  label: 'Resistance levels',    color: '#ef4444', default: true },
    { id: 'swings',      label: 'Swing H/L',            color: '#ec4899', default: true },
    { id: 'majors',      label: 'Major Highs/Lows',     color: '#f59e0b', default: true },
    { id: 'supply',      label: 'Supply zones',         color: 'rgba(239,68,68,0.25)', default: true },
    { id: 'demand',      label: 'Demand zones',         color: 'rgba(34,197,94,0.25)', default: true },
    { id: 'fvg',         label: 'Fair Value Gaps',      color: 'rgba(167,139,250,0.3)', default: true },
    { id: 'orderblock',  label: 'Order Blocks',         color: 'rgba(251,146,60,0.3)', default: true },
    { id: 'fib',         label: 'Fibonacci levels',     color: '#f59e0b', default: true },
    { id: 'vp',          label: 'Volume Profile (FRVP)', color: 'rgba(61,156,240,0.45)', default: true },
    { id: 'poc',         label: 'POC',                  color: '#22d3ee', default: true },
    { id: 'vahval',      label: 'VAH / VAL',            color: '#a3e635', default: true },
    { id: 'rsi',         label: 'RSI (subchart)',       color: '#a78bfa', default: true },
    { id: 'macd',        label: 'MACD (subchart)',      color: '#3d9cf0', default: false },
  ],

  colors: {
    bull: '#22c55e',
    bear: '#ef4444',
    wick: '#8b97a8',
    grid: 'rgba(30, 38, 54, 0.9)',
    crosshair: 'rgba(139, 151, 168, 0.5)',
    text: '#8b97a8',
    bg: '#0b0e14',
  },

  chart: {
    padL: 8,
    padR: 72,
    padT: 28,
    padB: 28,
    candleGap: 0.25,
  },
};

// Fundamental context templates (static educational snapshots)
CONFIG.fundamentals = {
  XAUUSD: {
    title: 'Gold (XAUUSD)',
    drivers: [
      'Real yields / US Treasury rates — inverse correlation often dominates',
      'USD strength (DXY) — stronger dollar typically weighs on gold',
      'Geopolitical risk & safe-haven flows',
      'Central bank gold purchases (net demand)',
      'Inflation expectations & real rates',
      'Fed / FOMC policy path and rate-cut odds',
    ],
    sessions: 'Most liquid during London & New York overlap. Watch US data (CPI, NFP, FOMC).',
    correlations: 'Often inverse to DXY and real yields; positive with risk-off equity stress.',
    notes: 'Gold is quoted in USD per troy ounce. Spot vs futures (GC) basis can differ slightly.',
  },
  EURUSD: {
    title: 'EUR/USD',
    drivers: [
      'ECB vs Fed policy differential',
      'Eurozone vs US growth & inflation data',
      'German Bunds / US Treasury yield spreads',
      'Risk sentiment (EUR is a risk-sensitive major)',
      'Energy prices (Eurozone terms of trade)',
      'Political developments in EU / US',
    ],
    sessions: 'Peak liquidity London open through NY morning. Major moves on ECB/Fed, CPI, PMI.',
    correlations: 'Often inverse to USD index; linked to EURCHF, EURGBP cross flows.',
    notes: 'Most traded FX pair. Pip value and spread typically tightest among majors.',
  },
  USOIL: {
    title: 'US Oil — WTI Crude',
    drivers: [
      'OPEC+ production decisions & compliance',
      'US inventory (EIA weekly) & SPR releases',
      'Global demand (China/India PMI, mobility)',
      'Geopolitics in Middle East / shipping lanes',
      'USD strength and risk appetite',
      'US rig count & shale production response',
    ],
    sessions: 'NYMEX hours matter; EIA inventory Wed 10:30 ET is a key catalyst.',
    correlations: 'Positive with energy equities & CAD; sensitive to global growth narrative.',
    notes: 'WTI (CL) vs Brent basis important. Contango/backwardation signals storage & demand.',
  },
  GBPJPY: {
    title: 'GBP/JPY',
    drivers: [
      'BoE vs BoJ policy differential (classic carry pair)',
      'UK inflation / wage data vs Japanese yields',
      'Global risk sentiment (JPY as funding / safe haven)',
      'UK political & fiscal news',
      'BoJ YCC / intervention rhetoric',
      'Equity risk appetite (pro-cyclical cross)',
    ],
    sessions: 'Tokyo + London overlap very active. Watch BoJ and BoE meeting days.',
    correlations: 'High beta to risk; tracks Nikkei/FTSE risk tone; sensitive to JPY crosses.',
    notes: 'Wide ranges and spikes common. Position sizing critical due to volatility.',
  },
  BTCUSD: {
    title: 'Bitcoin (BTC/USD)',
    drivers: [
      'Spot ETF flows & institutional demand',
      'Fed liquidity / real rates / DXY',
      'On-chain metrics (exchange reserves, MVRV, funding)',
      'Halving cycle narrative & miner behavior',
      'Regulatory headlines (SEC, global frameworks)',
      'Risk appetite & correlation with Nasdaq in risk-on/off',
    ],
    sessions: '24/7 market. Higher volume often around US equity hours & major macro prints.',
    correlations: 'Increasingly correlated with risk assets; still has crypto-specific catalysts.',
    notes: 'Data from Binance BTCUSDT (USD-margined proxy). Funding & open interest matter for shorts.',
  },
  ETHUSD: {
    title: 'Ethereum (ETH/USD)',
    drivers: [
      'ETH staking yield & supply dynamics (burn via EIP-1559)',
      'L2 activity, gas demand, DeFi TVL',
      'BTC beta — ETH often amplifies BTC moves',
      'ETF flows (spot ETH) when applicable',
      'Network upgrades & developer activity',
      'Stablecoin settlement & on-chain usage',
    ],
    sessions: '24/7. Watch US hours and major unlock / upgrade events.',
    correlations: 'High correlation with BTC; ETH/BTC ratio is a key relative-value gauge.',
    notes: 'Data from Binance ETHUSDT. Gas spikes can signal on-chain demand regimes.',
  },
};
